services:
  user-service:
    build: ./user-management
    ports:
      - "3001:3001"
    networks:
      - microservices-net

  asset-tracking-service:
    build: ./asset-tracking
    ports:
      - "3002:3002"
    networks:
      - microservices-net

  routing-service:
    build: ./routes
    ports:
      - "3443:3443"
    networks:
      - microservices-net

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  microservices-net:
    driver: bridge

volumes:
  pgdata:
