version: "3.9"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:5001"
    networks:
      - microservices-net

  data-service:
    build: ./data-service
    ports:
      - "3002:3002"
    networks:
      - microservices-net

  logging-service:
    build: ./logging-service
    ports:
      - "3003:3003"
    networks:
      - microservices-net

  routing-service:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge